version: "3.7"

services:
  cura-engine:
    build:
      context: .
      args:
        CURA_ENGINE_VERSION: ${CURA_ENGINE_VERSION}
    image: cura-engine:${CURA_ENGINE_VERSION}
    volumes:
      - ./output:/output
      - ./definitions:/definitions:ro
      - ./models:/models:ro
    command:
      - "bash"
      - "-c"
      # NOTE that -s settings are REQUIRED BEFORE OTHER parameters passed to CuraEngine
      - |
        for model in /models/*.stl; do
          /CuraEngine/build/Release/CuraEngine slice -p \
          -m6 \
          -s roofing_layer_count=1 \
          -s roofing_monotonic=true \
          -s cool_min_temperature=80 \
          -j /definitions/ultimaker_s3.def.json \
          -o /output/$$(basename $$model).gcode \
          -l $$model \
          -s support_enable=true \
          -s support_type=buildplate \
        ; done
